apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-gke
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: gcr.io/seminar-and-workshop/learn-gke:v1
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
