apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-gke
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: gcr.io/seminar-and-workshop/learn-gke:v1
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
