apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: learn-gke-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: learn-gke
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
